### ISSUE TITLE
ローディング画面の変更

### ISSUE THREAD

**Issue by monarsan** [sort-font/webpage#16]
待ち時間を短く感じさせるための何かを表示したい(例えば、間違い探しとか　フォントの豆知識とか)。　フォント関連のものだと良き。

**Comment by task4233** [comment]
## そもそもいるの？
- ローディング時間が10秒くらいで短いので、これ機能的にいらんくね？
- ローディング中に豆知識が出ても邪魔なだけじゃね
- 現状のままで良さそう

**Comment by task4233** [comment]
- これいらなそう
