### ISSUE TITLE
mainブランチにマージされた時点で、自動的にHerokuにデプロイする仕組みを導入する

### ISSUE THREAD

**Issue by task4233** [sort-font/webpage#31]
## どんな事
- mainブランチにマージされた時点で、自動的にHerokuにデプロイする仕組みを導入する

## そのために何をすれば良いのか
- GitHub Actionsのスクリプトを追加すれば良さそう

## それは何のために必要なのか
- 今のデプロイ方法は、僕が依存しているので良くない
- 他の人がマージした時でもデプロイできるようにしたい

## それを実現するために他の手法はないか
- CircleCI, Travis CIとかでも実現できるけど、GitHub Actionsが一番楽そう

ref: #26

**Comment by task4233** [comment]
下記の理由があるので、まだやってない
・developブランチ挟み込む必要があるので、作業中の人が誰もいない時にやりたい
・毎回デプロイするのは微妙そうな気もする

**Comment by monarsan** [comment]
## エラー発生
### エラー箇所
https://sort-font.herokuapp.com/index

### エラーメッセージ
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by task4233** [comment]
昼ごろ見ます
あざす

**Comment by task4233** [comment]
mainブランチにマージされた時に自動デプロイする設定は追加しといた
(マージ後結構時間かかるかもしれないので、1時間を目安に思ってもらうと良さそう)
動くかどうかは今度見てもらわんとわからん。

それと、ひとまずバグは解消しといた。
ref: #48

**Comment by task4233** [comment]
できてそう

![スクリーンショット 2021-09-10 9 03 22](https://user-images.githubusercontent.com/29667656/132777909-dd8d73e8-6ef2-4f0c-8567-a166ee911d80.png)

これで僕がいなくても、PRをマージして少し待てば最新のmainのコードがデプロイされるはず。
