### ISSUE TITLE
入力画像をうまく白黒画像に変換したい

### ISSUE THREAD

**Issue by monarsan** [sort-font/webpage#39]
## 概要
入力画像をうまく白黒画像に変換したい

## なぜ必要なのか
白黒でない画像を入力すると、高い確率で gen jiyuu gothic p hold というフォントに分類され、うまく推論できていないから。
教師データが白黒だったから、それに合わせたい。

**Comment by task4233** [comment]
server.py内部で,"L"指定でconvertを実行すると良い気がしました 

Image.convert(mode=None, matrix=None, dither=None, palette=0, colors=256)
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert

**Comment by task4233** [comment]
refer #17
